script:
- |
  git config user.name "Zilliqa Maintainers"
  git config user.email "maintainers@zilliqa.com"
  git remote add source https://$GITHUB_PERSONAL_TOKEY@github.com/Zilliqa/Zilliqa-wiki.git > /dev/null 2>&1
  git remote add wiki https://$GITHUB_PERSONAL_TOKEY@github.com/Zilliqa/Zilliqa.wiki.git > /dev/null 2>&1
  git fetch source
  git fetch wiki
  git merge source/master --no-edit
  git push source HEAD:master > /dev/null 2>&1
  git push wiki HEAD:master > /dev/null 2>&1